import IMG_test from '../../asets/MX472.jpeg';

export const StoreData = [
  {
    _id: "1",
    image: IMG_test,
    tittle: 'test product1',
    categori: 'test1',
    description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque tempora omnis molestias dolores veritatis cum architecto consequuntur pariatur. Voluptate itaque sit error suscipit doloribus numquam esse facere recusandae mollitia temporibus.',
    price: 100,
    numReviews: 3,
    inStock:10,
  },
  {
    _id: "2",
    image: IMG_test,
    tittle: 'test product2',
    categori: 'test1',
    description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque tempora omnis molestias dolores veritatis cum architecto consequuntur pariatur. Voluptate itaque sit error suscipit doloribus numquam esse facere recusandae mollitia temporibus.',
    price: 100,
    numReviews: 3,
    inStock:4,
  },
  {
    _id: "3",
    image: IMG_test,
    tittle: 'test product3',
    categori: 'test2',
    description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque tempora omnis molestias dolores veritatis cum architecto consequuntur pariatur. Voluptate itaque sit error suscipit doloribus numquam esse facere recusandae mollitia temporibus.',
    price: 100,
    numReviews: 3,
    inStock:4,
  },
  {
    _id: "4",
    image: IMG_test,
    tittle: 'test product4',
    categori: 'test2',
    description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque tempora omnis molestias dolores veritatis cum architecto consequuntur pariatur. Voluptate itaque sit error suscipit doloribus numquam esse facere recusandae mollitia temporibus.',
    price: 100,
    numReviews: 3,
    inStock:4,
  },
  {
    _id: "5",
    image: IMG_test,
    tittle: 'test product5',
    categori: 'test3',
    description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque tempora omnis molestias dolores veritatis cum architecto consequuntur pariatur. Voluptate itaque sit error suscipit doloribus numquam esse facere recusandae mollitia temporibus.',
    price: 100,
    numReviews: 3,
    inStock:4,
  },
  {
    _id: "6",
    image: IMG_test,
    tittle: 'test product6',
    categori: 'test3',
    description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque tempora omnis molestias dolores veritatis cum architecto consequuntur pariatur. Voluptate itaque sit error suscipit doloribus numquam esse facere recusandae mollitia temporibus.',        
    price: 100,
    numReviews: 3,
    inStock:4,
  },
  {
    _id: "7",
    image: IMG_test,
    tittle: 'test product7',
    categori: 'test4',
    description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque tempora omnis molestias dolores veritatis cum architecto consequuntur pariatur. Voluptate itaque sit error suscipit doloribus numquam esse facere recusandae mollitia temporibus.',
    price: 100,
    numReviews: 3,
    inStock:7,
  },
  {
    _id: "8",
    image: IMG_test,
    tittle: 'test product8',
    categori: 'test4',
    description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque tempora omnis molestias dolores veritatis cum architecto consequuntur pariatur. Voluptate itaque sit error suscipit doloribus numquam esse facere recusandae mollitia temporibus.',
    price: 100,
    numReviews: 3,
    inStock:4,
  },
  {
    _id: "9",
    image: IMG_test,
    tittle: 'test product9',
    categori: 'test5',
    description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque tempora omnis molestias dolores veritatis cum architecto consequuntur pariatur. Voluptate itaque sit error suscipit doloribus numquam esse facere recusandae mollitia temporibus.',
    price: 100,
    numReviews: 3,
    inStock:4,
  },
  {
    _id: "10",
    image: IMG_test,
    tittle: 'test product10',
    categori: 'test5',
    description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque tempora omnis molestias dolores veritatis cum architecto consequuntur pariatur. Voluptate itaque sit error suscipit doloribus numquam esse facere recusandae mollitia temporibus.',
    price: 100,
    numReviews: 3,
    inStock:3,
  },
  {
    _id: "11",
    image: IMG_test,
    tittle: 'test product11',
    categori: 'test5',
    description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque tempora omnis molestias dolores veritatis cum architecto consequuntur pariatur. Voluptate itaque sit error suscipit doloribus numquam esse facere recusandae mollitia temporibus.',
    price: 100,
    numReviews: 3,
    inStock:10,
  },

];
